start-at-login = true

on-focused-monitor-changed = 'move-mouse monitor-lazy-center'
on-focus-changed = 'exec-and-forget ~/.config/aerospace/bin/on_focus_changed'

automatically-unhide-macos-hidden-apps = false

[[on-window-detected]]
    run = 'exec-and-forget ~/.config/aerospace/bin/on_new_window'

[mode.main.binding]

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'
    alt-0 = 'workspace 0'

    alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1', 'exec-and-forget ~/.config/aerospace/bin/toggle_workspace_layout']
    alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2', 'exec-and-forget ~/.config/aerospace/bin/toggle_workspace_layout']
    alt-shift-3 = ['move-node-to-workspace 3', 'workspace 3', 'exec-and-forget ~/.config/aerospace/bin/toggle_workspace_layout']
    alt-shift-4 = ['move-node-to-workspace 4', 'workspace 4', 'exec-and-forget ~/.config/aerospace/bin/toggle_workspace_layout']
    alt-shift-5 = ['move-node-to-workspace 5', 'workspace 5', 'exec-and-forget ~/.config/aerospace/bin/toggle_workspace_layout']
    alt-shift-6 = ['move-node-to-workspace 6', 'workspace 6', 'exec-and-forget ~/.config/aerospace/bin/toggle_workspace_layout']
    alt-shift-7 = ['move-node-to-workspace 7', 'workspace 7', 'exec-and-forget ~/.config/aerospace/bin/toggle_workspace_layout']
    alt-shift-8 = ['move-node-to-workspace 8', 'workspace 8', 'exec-and-forget ~/.config/aerospace/bin/toggle_workspace_layout']
    alt-shift-9 = ['move-node-to-workspace 9', 'workspace 9', 'exec-and-forget ~/.config/aerospace/bin/toggle_workspace_layout']
    alt-shift-0 = ['move-node-to-workspace 0', 'workspace 0', 'exec-and-forget ~/.config/aerospace/bin/toggle_workspace_layout']

    alt-h = 'focus left'
    alt-l = 'focus right'

    alt-shift-h = 'move left'
    alt-shift-l = 'move right'

    alt-f = 'layout floating tiling'
    alt-r = 'reload-config'

